import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        ArrayList<Integer> numeros = new ArrayList<Integer>(); // En esta línea se crea un ArrayList de enteros
        numeros.add(10); // Se añade el número 10 al ArrayList
        numeros.add(20); // Se añade el número 20 al ArrayList
        numeros.add(30);
        numeros.add(40); 
        numeros.add(50); 
        System.out.println(numeros.get(0)); 

        String[] animales = {"Perro", "Gato", "Pájaro", "Conejo" };  // Se crea un arreglo de cadenas
    } 
} 